name: Auto Assign to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Project
    steps:
    - name: Assign NEW issues and NEW pull requests to the frontend 2021 project
      uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/hackathon/hackthenorth.com/projects/2'
